config/routes.rb
Property::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   resources :welcomes do
     collection do
       get :user_type
     end
   end

   resources :users  do
     collection do
       get :home
     end
   end

   resources :propertydetails do
     collection do
     end
   end

   resources :buyerprofiles

   resources :search_properties do
     collection do
       get :search_property
       get :search_property_by_city
     end
   end

   resources :agreements do
     collection do
       get :generate_agreement
     end
   end

   root :to => 'welcomes#welcome'

end

app/models/property_detail.rb
class PropertyDetail < ActiveRecord::Base

  DEFAULT_PROPERTY_IMAGE = "/assets/default_property_image.png"

  PER_PAGE_SIZE = {:per_page_size => 5}


  attr_accessible :address, :area, :city, :country, :price, :property_type, :sold_status, :state, :user_id, :pictures_attributes

  has_many :pictures, as: :imageable
  accepts_nested_attributes_for :pictures
  belongs_to :user
  has_many :agreements

  validates_presence_of :area, :city, :country, :price, :state, :address

  SOLD_STATUS = {:sold => 'Sold', :not_sold => 'Not Sold'}

  PROPERTY_TYPE = {'residential' => 'Residential', 'commercial' => "Commercial"}

  scope :property_by_city_and_budget, lambda {|city, min_budget, max_budget| where(:city => city, :price => min_budget.to_i .. max_budget.to_i)}

  def self.property_count_by_city_and_budget(city, min_budget, max_budget)
    PropertyDetail.where(:city =>city, :price => min_budget .. max_budget).count
  end

	def self.property_by_city(city)
		self.where(:city => city)
	end

end

app/controllers/propertydetails_controller.rb
class PropertydetailsController < ApplicationController
  before_filter :authenticate_user!
  
  def new 
    @prop = PropertyDetail.new
  end
  
  def create 
    @prop = current_user.property_details.new(params[:property_detail])
    if @prop.save
      flash[:notice] = "New Property has been created successfully"
      redirect_to home_users_path
    else
      flash[:error] = @prop.errors.full_messages.join("<br/>")
    end
  end
  def index
    @prop = current_user.property_details.paginate(:page => params[:page], :per_page => PropertyDetail:: PER_PAGE_SIZE["per_page_size"])
  end
  
  def show
    @prop = current_user.property_details.find(params[:id])
  end
  
  def edit
    @prop = current_user.property_details.find(params[:id])
  end
  
  def update
    prop = current_user.property_details.find(params[:id])
    if prop.update_attributes(params[:property_detail])
      flash[:notice] = "Property details has been updated successfully"
      redirect_to home_users_path
    end
  end
  
  def destroy
    prop = current_user.property_details.find(params[:id])
    sprop.destroy
    flash[:notice] = "Property has been destroyed successfully"
    redirect_to home_users_path
  end
end

app/helpers/propertydetails_helper.rb
module PropertydetailsHelper
end

app/views/propertydetails/edit.html.erb
<div class="container  border_and_background">
  <h2>Edit Property Details</h2>
  <%= form_for(@prop, :url => propertydetail_path(@prop.id), :method => :put ) do |f| %>
    <div class="row-fluid">
      <div class="span12 margin_left ">
        <div class="row-fluid">
          <div class="row-fluid">
            <div class="span2 ">
              <%= f.label :property_type %>
            </div>
            <div class="span4">
              <%= f.select(:property_type, options_for_select([[PropertyDetail::PROPERTY_TYPE["residential"], 'Residential'], [PropertyDetail::PROPERTY_TYPE["commercial"], 'Commercial']] , :selected => params[:property_type])) %>
            </div>
            <div class="span2">
              <%= f.label :area %>
            </div>
            <div class="span4">
              <%= f.text_field :area %>
            </div>
          </div>
          <div class="row-fluid">
            <div class="span2">
              <%= f.label :price %>
            </div>
            <div class="span4">
              <%= f.text_field :price %>
            </div>
            <div class="span2">
              <%= f.label :country %>
            </div>
            <div class="span4">
              <%= f.text_field :country %>
            </div>
          </div>
          <div class="row-fluid">
            <div class="span2">
              <%= f.label :state %>
            </div>
            <div class="span4">
              <%= f.text_field :state %>
            </div>
             <div class="span2">
              <%= f.label :city %>
            </div>
            <div class="span4">
              <%= f.text_field :city %>
            </div>
          </div>
          <div class="row-fluid">
            <div class="span2">
              <%= f.label :address %>
            </div>
            <div class="span4">
              <%= f.text_field :address %>
            </div>
          </div>
          <div class="row-fluid">
            <div class="span1">
             <%= f.submit "Update", :class => 'btn btn-success btn-min'  %>
            </div>
            <div class="span1">
              <%= link_to "Back", :back, :class => 'btn btn-info btn-min' %>
            </div>
          </div>
        </div> 
      </div> 
    </div>
  <% end %>
</div>

app/views/propertydetails/index.html.erb
<div class="border_and_background span12">
  <h2>List of properties</h2>
  <input id="seach_property" tyep=""text placeholder="Type city name">
  <div class="row-fluid margin_left">
    <div class="row-fluid">
      <div class="span3"><strong>Type</strong></div>
      <div class="span3"><strong>Price</strong></div>
      <div class="span3"><strong>Post Date</strong></div>
    </div>
    <%@prop.each do |p| %> 
      <div class="row-fluid">
        <div class="span3"><%= link_to p.property_type, propertydetail_path(p)%></div>
        <div class="span3"><%= p.price%></div>
        <div class="span3"><%= p.created_at.strftime("%Y/%m/%d") %></div>
        <div class="span3">
          <%= link_to 'Edit', edit_propertydetail_path(p), :class => 'btn btn-primary btn-small' %>
          <%= link_to 'Destroy', propertydetail_path(p), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger btn-small' %>
        </div>
      </div>
    <%end%> 
    <div class="row-fluid">
      <div class="span3">
       <%= will_paginate @prop %>
      </div>  
    </div>
    <div class="row-fluid">
      <div class="span3 margin_top">
       <%= link_to 'Back', home_users_path, :class => 'btn btn-info btn-min' %>
      </div>  
    </div>
  </div>
</div>

app/views/propertydetails/new.html.erb
<% @prop.pictures.build %>
<h3>Add New Property</h3>
<%= form_for(@prop, :id => "new_property", :url => propertydetails_path(@prop) , :method => :post, :validate => true, :html => {:multipart => true} ) do |f| %>
  <div class="row-fluid">
    <div class="span10">
      <div class="row-fluid">
        <div class="row-fluid">
          <div class="span5"><%= f.select :property_type, ['Select Property Type',[PropertyDetail::PROPERTY_TYPE["residential"], 'Residential'], [PropertyDetail::PROPERTY_TYPE["commercial"], 'Commercial']] %></div>
          <div class="span5"><%= f.text_field :area, :placeholder => "Enter area", :required =>"required" %>(in sqr. feet)</div>
        </div>
        <div class="row-fluid">
          <div class="span5"><%= f.text_field :price, :placeholder => "Enter price", :required =>"required"%></div>
          <div class="span5"><%= f.text_field :country , :placeholder => "Enter country", :required =>"required"%></div></div>
        </div>
        <div class="row-fluid">
          <div class="span5"><%= f.text_field :state , :placeholder => "Enter state", :required =>"required"%></div>
          <div class="span5"><%= f.text_field :city , :placeholder => "Enter city", :required =>"required"%></div>
        </div>
        <div class="row-fluid">
          <div class="span5"><%= f.text_field :address, :placeholder => "Enter address", :required =>"required" %></div>
        </div>
        <%=f.hidden_field :sold_status, :value => params[:status]%>
        <div class="row-fluid">
          <div class="span5">
            <%= f.fields_for :pictures do |pic_form| %>
            <%= pic_form.file_field :image %>
            <% end %>
          </div>
        </div>
        <div class="row-fluid">
          <div class="span1"><%= f.submit "Add", :class => 'btn btn-success btn-min', :id => "add_btn" %></div>
          <div class="span1"><%= link_to 'Back', :back , :class => 'btn btn-info btn-min' %></div>
        </div>  
       </div>    
     </div>
  </div>
<% end %>

app/views/propertydetails/show.html.erb
<h2>Property Details</h2><br>
<div class="row-fluid pull-left ">
  <div class="span6 border_and_background left_col_height">
    <div class="row-fluid margin_left">
      <div class="row-fluid">
        <div class="span4"><strong>Property Type  :</strong></div>
        <div class="span3"><%= @prop.property_type %></div>
      </div>  
      <div class="row-fluid">
        <div class="span4"><strong>Area in Sqr. Feet :</strong></div> 
        <div class="span3"><%= @prop.area %></div>
      </div> 
      <div class="row-fluid">
        <div class="span4"><strong>Price  :</strong></div> 
        <div class="span3"><%= @prop.price %></div>
      </div> 
      <div class="row-fluid">
        <div class="span4"><strong>Country : </strong></div>
        <div class="span3"><%= @prop.country %></div>
      </div> 
      <div class="row-fluid">
        <div class="span4"><strong>State : </strong></div>
        <div class="span3"><%= @prop.state %></div>
      </div> 
      <div class="row-fluid">
        <div class="span4"><strong>City :</strong></div> 
        <div class="span3"><%= @prop.city %></div>
      </div>  
      <div class="row-fluid">
        <div class="span4"><strong>Location :</strong></div> 
        <div class="span3"><%= @prop.address %> </div>
      </div>  
    </div>
  </div>
  <div class="span4"> 
    <div class="row-fluid">
      <div class="row-fluid">
        <div class="span8"><%= image_tag(property_image(@prop), size: "200x200") %></div>
      </div>  
    </div>  
  </div>
</div>
<%= link_to 'Back', :back, :class => 'btn btn-info btn-min' %>


 