config/routes.rb
Property::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   resources :welcomes do
     collection do
       get :user_type
     end
   end

   resources :users  do
     collection do
       get :home
     end
   end

   resources :propertydetails do
     collection do
     end
   end

   resources :buyerprofiles

   resources :search_properties do
     collection do
       get :search_property
       get :search_property_by_city
     end
   end

   resources :agreements do
     collection do
       get :generate_agreement
     end
   end

   root :to => 'welcomes#welcome'

end

app/models/buyer_profile.rb
class BuyerProfile < ActiveRecord::Base
  attr_accessible :user_id, :looking_city, :looking_country, :max_budget, :min_budget, :property_type
  
  belongs_to :user
  
  validates_presence_of :looking_city, :max_budget, :min_budget
  
  after_create :property_notfication
  
  def property_notfication
    PropertyNotifier.property_notfication_mail(self).deliver
  end
  
end

app/controllers/buyerprofiles_controller.rb
class BuyerprofilesController < ApplicationController
  before_filter :authenticate_user!

  def show
    @buyer = buyer_profiles_info
  end
  
  def new
    @buyer = BuyerProfile.new
  end  
 
  def create
    @buyer = current_user.buyer_profiles.new(params[:buyer_profile])
    if @buyer.save
      flash[:notice] = "Your property profile created successfully"
      redirect_to home_users_path
    else
      flash[:error] = @buyer.errors.full_messages.join("<br/>")
    end
  end
  
  def edit
    @buyer = buyer_profiles_info
  end
  
  def update
    buyer = buyer_profiles_info
    if buyer.update_attributes(params[:buyer_profile])
      flash[:notice] = "Your property profile updated successfully"
      redirect_to home_users_path
    end
  end
  
  private
  
  def buyer_profiles_info
    current_user.buyer_profiles.find(params[:id])
  end
end

app/helpers/buyerprofiles_helper.rb
module BuyerprofilesHelper
end

app/views/buyerprofiles/edit.html.erb
<div class="container  border_and_background">
  <h5>Edit Your Property Profile</h5>
  <%= form_for(@buyer, :url => buyerprofile_path(@buyer.id), :method => :put ) do |f| %>
    <div class="row-fluid">
      <div class="span12 margin_left left_col_height">
        <div class="row-fluid">
          <div class="row-fluid">
            <div class="span2">
              <%= f.label :property_type %>
            </div>
            <div class="span4">
              <%= f.select(:property_type, options_for_select([[PropertyDetail::PROPERTY_TYPE["residential"], 'Residential'], 
              [PropertyDetail::PROPERTY_TYPE["commercial"], 'Commercial']] , :selected => params[:property_type])) %>
            </div>
            <div class="span2">
              <%= f.label :min_budget %>
            </div>
            <div class="span4">
              <%= f.text_field :min_budget %>
            </div>
          </div>
          
          <div class="row-fluid">
            <div class="span2">
              <%= f.label :max_budget %>
            </div>
            <div class="span4">
              <%= f.text_field :max_budget %>
            </div>
            <div class="span2">
              <%= f.label :looking_country %>
            </div>
            <div class="span4">
              <%= f.text_field :looking_country %>
            </div>
          </div>
          
          <div class="row-fluid">
            <div class="span2">
              <%= f.label :looking_city %>
            </div>
            <div class="span4">
              <%= f.text_field :looking_city %>
            </div>
          </div>
                  
          <div class="row-fluid">
            <div class="span1 ">
             <%= f.submit "Update", :class => 'btn btn-success btn-min'  %>
            </div>
            <div class="span1 ">
              <%= link_to "Back", home_users_path, :class => 'btn btn-info btn-min' %>
            </div>
          </div><br/> 
        </div> 
      </div> 
    </div>
  <% end %>
</div>

app/views/buyerprofiles/new.html.erb
<div class="container  border_and_background">
  <h2>We need some information from you</h2>
  <%= form_for(@buyer, :url => buyerprofiles_path(@buyer) , :method => :post,  :html => {:multipart => true} ) do |f| %>
    <div class="row-fluid">
    <div class="span12 left_col_height margin_left">
      <div class="row-fluid">
        <div class="row-fluid">
          <div class="span5"><%= f.select :property_type, ['Select Property Type','Residential', 'Commercial'] %></div>
          <div class="span5"><%= f.text_field :min_budget, :placeholder => "Yours minimum budget", :required=>"required"%></div>
        </div>
        <div class="row-fluid">
          <div class="span5"><%= f.text_field :max_budget , :placeholder => "Yours maximum budget", :required=>"required"%></div>
          <div class="span5"><%= f.text_field :looking_country , :placeholder => "Looking in which country", :required=>"required"%></div>
        </div>
        <div class="row-fluid">
          <div class="span5"><%= f.text_field :looking_city , :placeholder => "Looking in which city", :required=>"required"%></div>
        </div>
        <div class="row-fluid">
          <div class="span1"><%= f.submit "Submit", :class => 'btn btn-success btn-min' %></div>
          <div class="span1"><%= link_to 'Back', :back , :class => 'btn btn-info btn-min' %></div>
        </div>  
       </div>    
     </div>
   </div>
  <% end %>
  </div>
</div>

app/views/buyerprofiles/show.html.erb
<h5>Your Property Profile</h5>
<div class="row-fluid pull-left ">
  <div class="span8 border_and_background left_col_height">
    <div class="row-fluid margin_left">
      <div class="row-fluid">
        <div class="span4"><strong>Property Type  :</strong></div>
        <div class="span3"><%= @buyer.property_type%></div>
      </div>
      <div class="row-fluid">
        <div class="span4"><strong>Minimum Budget :</strong></div>
        <div class="span3"><%= @buyer.min_budget%></div>
      </div>
      <div class="row-fluid">
        <div class="span4"><strong>maximum Budget :</strong></div>
        <div class="span3"><%= @buyer.max_budget%></div>
      </div>  
      <div class="row-fluid">
        <div class="span4"><strong>Looking Country :</strong></div>
        <div class="span3"><%= @buyer.looking_country%></div>
      </div>  
      <div class="row-fluid">
        <div class="span4"><strong>Looking City :</strong></div>
        <div class="span3"><%= @buyer.looking_city%></div>
      </div>  
    </div>
  </div>
</div>
<%= link_to 'Edit', edit_buyerprofile_path(@buyer.id), :class => 'btn btn-success btn-min' %>
<%= link_to 'Back', home_users_path, :class => 'btn btn-info btn-min' %>


 