config/routes.rb
Property::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   resources :welcomes do
     collection do
       get :user_type
     end
   end

   resources :users  do
     collection do
       get :home
     end
   end

   resources :propertydetails do
     collection do
     end
   end

   resources :buyerprofiles

   resources :search_properties do
     collection do
       get :search_property
       get :search_property_by_city
     end
   end

   resources :agreements do
     collection do
       get :generate_agreement
     end
   end

   root :to => 'welcomes#welcome'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :github, :twitter]
  
  USER_TYPE = {:seller => 'Seller', :buyer => 'Buyer'} 
  DEFAULT_USER_IMAGE  = "/assets/default_user_image.png"
  MOBILE_MIN_SIZE = 10
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :gender, :mobile, :dob, :user_type, :country, :state, :city, :address, :zip_code, :pictures_attributes
  attr_accessible :provider, :uid
 
  #validates_presence_of :first_name, :last_name, :mobile, :city, :country, :state, :address, :zip_code
  #validates_length_of :mobile, :minimum => MOBILE_MIN_SIZE
  
  has_many :pictures, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :pictures
  
  has_many :property_details, dependent: :destroy
  
  has_many :buyer_profiles, dependent: :destroy
  
  has_many :agreements, dependent: :destroy
  
  
  def username
    "#{self.first_name} #{self.last_name}" 
  end
  
  def self.find_for_facebook_oauth(provider, uid, first_name, email, signed_in_resource=nil)
    user = User.where(:provider => provider, :uid => uid).first
    unless user
      user = User.create(:first_name => name,
                     :provider => provider,
                     :uid => uid,
                     :email => email,
                     :password => Devise.friendly_token[0,20]
                     )

    end
    return user
  end
  
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(first_name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
  end
  
  def self.find_for_github_auth(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(first_name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
  end
  
  def self.find_for_twitter_auth(access_token, signed_in_resource=nil)
    debugger
    data = access_token.info
    user = User.where(:uid => data["uid"]).first if data["uid"].present?
    unless user
        user = User.create(uid: data["uid"],
             email: data["uid"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    #@user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"].provider, request.env["omniauth.auth"].uid, request.env["omniauth.auth"].extra.raw_info.name, request.env["omniauth.auth"].info.email, current_user)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].uid
      redirect_to new_user_registration_url
    end
  end
  
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
  
  def github
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_github_auth(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "github"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.github_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end 
  end

  def twitter
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_twitter_auth(request.env["omniauth.auth"].except("extra"), current_user)
      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "twitter"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:home]

  def home  
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<p class = "notice"></p> 
<div class="row-fluid">
  <div class="span3 border_and_background left_col_height">
    <div class="row-fluid margin_left">
      <%if current_user.user_type == User::USER_TYPE[:seller]%>
        <div class="row-fluid">
          <div class="span12"><%= link_to "Post new Property",new_propertydetail_path(:status => PropertyDetail::SOLD_STATUS[:not_sold])%></div>
        </div>  
        <div class="row-fluid">
          <div class="span12"><%= link_to "View Property", propertydetails_path %></div>
        </div>  
      <%else%>
        <div class="row-fluid">
          <div class="span12"><%= link_to "Search Property",search_properties_path%></div>
        </div>  
        <div class="row-fluid">
          <div class="span12"><%= link_to "Create Property Profile", new_buyerprofile_path %></div>
        </div> 
        <div class="row-fluid">
          <% if current_user.buyer_profiles.present? %>
          <div class="span12"><%= link_to "View Property Profile", buyerprofile_path(current_user.buyer_profiles.last.id)%></div>
          <%end%>
        </div>
      <%end%> 
    </div>
  </div>
  
  <div class="span9 border_and_background left_col_height"> 
    <div class="row-fluid margin_left">
      <div class="row-fluid">
        <div class="span3"><strong>User Type:</strong></div>
        <div class="span6"><%= current_user.user_type %></div>
      </div>  
      <div class="row-fluid">
        <div class="span3"><strong>Name:</strong></div>
        <div class="span6"><%= current_user.username %></div>
      </div>
      <div class="row-fluid">
        <div class="span3"><strong>Mobile No:</strong></div>
        <div class="span6"><%= current_user.mobile %></div>
      </div>  
      <div class="row-fluid">
        <div class="span3"><strong>Gender:</strong></div>
        <div class="span6"><%= current_user.gender %></div>
      </div>  
      <div class="row-fluid">
        <div class="span3"><strong>Email:</strong></div>
        <div class="span6"><%= current_user.email %></div>
      </div>
      <div class="row-fluid">
        <div class="span3"><strong>Country:</strong></div>
        <div class="span6"><%= current_user.country %></div>
      </div> 
      <div class="row-fluid">
        <div class="span3"><strong>State:</strong></div>
        <div class="span6"><%= current_user.state %></div>
      </div>   
      <div class="row-fluid">
        <div class="span3"><strong>City:</strong></div>
        <div class="span6"><%= current_user.city %></div>
      </div>
      <div class="row-fluid">
        <div class="span3"><strong>Address:</strong></div>
        <div class="span6"><%= current_user.address %></div>
      </div> 
      <div class="row-fluid">
        <div class="span3"><strong>Zip Code:</strong></div>
        <div class="span6"><%= current_user.zip_code %></div>
      </div> 
    </div>  
  </div>
  
</div>