config/routes.rb
Property::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   resources :welcomes do
     collection do
       get :user_type
     end
   end

   resources :users  do
     collection do
       get :home
     end
   end

   resources :propertydetails do
     collection do
     end
   end

   resources :buyerprofiles

   resources :search_properties do
     collection do
       get :search_property
       get :search_property_by_city
     end
   end

   resources :agreements do
     collection do
       get :generate_agreement
     end
   end

   root :to => 'welcomes#welcome'

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert_margin alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    </div>
  <% end %>
  <% flash.discard(name) %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= stylesheet_link_tag "custom" %>
  <nav>
  All rights and content are Copyright © 2013
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div align=left class="container">
      <div class="container-fluid">
       <nav>
          <ul class="nav pull-left">
            <% if user_signed_in? %>
              <li><%= link_to "Home", home_users_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path%><li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %><li>
             <%else%>
              <li><%= link_to "Sign in", user_session_path %></li>
              <li><%= link_to "Sign up", user_type_welcomes_path%></li>
            <%end%>
          </ul>
          <div class="div_color t" align="right">
              <% unless current_user.blank? %>
                <%= current_user.username %>
                  <%= image_tag(user_profile_image, size: "50x50", :crop => :fill, :radius => 20) %>
              <%end%>
         </div>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Property</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", controller_name %>
  <%= csrf_meta_tags %>
</head>
<body><br/><br/><br/>
  <%= render 'layouts/header' %>
  
  <div class="container">
    <%= link_to image_tag('facebook_logo_50x50.png', size: "30x30"), user_omniauth_authorize_path(:facebook) %>
    <%= link_to image_tag('Twitter-icon-50x50.png', size: "30x30"), user_omniauth_authorize_path(:twitter) %>
    <%= link_to image_tag('google.png', size: "30x30"), user_omniauth_authorize_path(:google_oauth2) %>
    <%= link_to image_tag('github.png', size: "30x30"), user_omniauth_authorize_path(:github) %>
    
    <%= render :partial => 'layouts/flash_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>